services:
  app:
    container_name: backoffice-portal-app
    build:
      context: ./apps/backoffice-portal
      dockerfile: Dockerfile
    ports:
      - '3200:3200'
    networks:
      - backoffice-portal-net

  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./apps/backoffice-portal/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - '81:80'
    networks:
      - backoffice-portal-net

networks:
  backoffice-portal-net:
